<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Fibonacci game</title>
<script language="javascript" src="./jsgame.js"></script>
<script language="javascript">
// BEGIN AUTOGENERATED CODE
// @@#include "./jsgame.js"
// END AUTOGENERATED CODE

var field;

var mouseDownX;
var mouseDownY;

function startx() {
	field = game.NewField();
	field.AddPoint();
	field.AddPoint();

	drawField();
}

function drawField() {
	var colorMap = {
		1: "#bbbbbb",
		2: "#ffff55",
		3: "#00af00",
		5: "#5555ff",
		8: "#008787",
		13: "#aa00aa",
		21: "#cc0000",
		34: "#f0f0a0",
		55: "#55ff55",
		89: "#6060bb",
		144: "#94e13a",
	};
	var board = document.getElementById('mainBoard');

	while( board.firstChild ) {
		board.removeChild(board.firstChild);
	}

	for (var y=0; y<4; y++){
		for (var x=0; x<4; x++) {
			var value = field.Get(y, x);
			var div = document.createElement("div");
			div.className = "boardCell";
			div.style.fontWeight = 'bold';
			if (value > 0) {
				var text = document.createTextNode(value);
				div.appendChild(text);
				if (colorMap[value]) {
					div.style.backgroundColor = colorMap[value];
				}
			}
			board.appendChild(div);
		}
	}

	// draw score
	var score = document.getElementById('score');
	while( score.firstChild ) {
		score.removeChild(score.firstChild);
	}
	score.appendChild(document.createTextNode(field.Score()));

	// draw sequence
	var seq = document.getElementById('sequence')
	while( seq.firstChild ) {
		seq.removeChild(seq.firstChild);
	}
	var fs = field.Sequence();
	var seqText = "";
	for (var i=0; i<fs.length; i++) {
		seqText += "  " + fs[i];
	}
	seqText += "  ...";
	seq.appendChild(document.createTextNode(seqText));
}

function toogleHelp() {
	var score = document.getElementById('hint');
	score.hidden = !score.hidden;
}

function handleKey(event) {
	var keymaps = {
		37:	game.Left,  // left
		40: game.Down,  // down
		38: game.Up,    // up
		39: game.Right, // right

		65:	game.Left,  // a
		83: game.Down,  // s
		87: game.Up,    // w
		68: game.Right, // d

		72:	game.Left,  // h
		74: game.Down,  // j
		75: game.Up,    // k
		76: game.Right, // l
	}
	var keyCode = ('which' in event) ? event.which : event.keyCode;

	if (keyCode == 191) {
		// '/'
		toogleHelp();
		return;
	}

	var dir = keymaps[keyCode];
	fieldMove(dir);
}

function fieldMove(dir) {
	if (dir) {
		var moved = field.Move(dir);
		if (moved) {
			field.AddPoint();
		}
	}
	drawField();
}

window.addEventListener('load', function(){ // on page load
 
    document.body.addEventListener('touchstart', function(e){
		mouseDownX = e.changedTouches[0].pageX;
		mouseDownY = e.changedTouches[0].pageY;
    }, false);

    document.body.addEventListener('touchend', function(e){
		var x = e.changedTouches[0].pageX;
		var y = e.changedTouches[0].pageY;
		if (mouseDownX > 0 && mouseDownY > 0) {
			var dx = x - mouseDownX;
			var dy = y - mouseDownY;
			if (Math.abs(dy) * 2 < Math.abs(dx)) {
				if (dx > 80) {
					fieldMove(game.Right);
				}
				if (dx < -80) {
					fieldMove(game.Left);
				}
			}
			if (Math.abs(dx) * 2 < Math.abs(dy)) {
				if (dy > 80) {
					fieldMove(game.Down);
				}
				if (dy < -80) {
					fieldMove(game.Up);
				}
			}
		}
		mouseDownX = 0;
		mouseDownY = 0;

	}, false);
 
}, false)

</script>
<style>
#mainBoard
{
	width:400px;
	height:400px;
	/* float:center;*/
}

.boardCell
{
	width:98px;
	height:98px;
	float:left;
	border:1px solid black;
	line-height: 98px;
	font-weight: bold;
	font-size: 3em;
}

</style>
</head>
<body onload="startx()" onkeydown="handleKey(event)">
<center>
	<div id="content">
		<h1>Fibonacci game</h1>
		<p>Score:&nbsp;<span id="score"></div></p>
		<br/>
		<p><div id="mainBoard"></div></p>
		<br/>
		<p><span id="sequence"></span></p>
		<p><span id="hint" title="use arrow keys (or WASD or even HJKL) or swipe to move tiles, try summing Fibonacci numbers!">?</span></p>
	</div>
</center>

</body>
</html>
<!-- vim: set ft=html: -->
