<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Fibonacci game</title>
<script language="javascript" src="./jsgame.js"></script>
<script language="javascript">
// BEGIN AUTOGENERATED CODE
// @@#include "./jsgame.js"
// END AUTOGENERATED CODE

var field;

function startx() {
	field = game.NewField();
	field.AddPoint();
	field.AddPoint();

	drawField();
}

function drawField() {
	var board = document.getElementById('mainBoard');

	while( board.firstChild ) {
		board.removeChild(board.firstChild);
	}

	for (var y=0; y<4; y++){
		for (var x=0; x<4; x++) {
			var value = field.Get(y, x);
			var div = document.createElement("div");
			div.className = "boardCell";
			if (value > 0) {
				var text = document.createTextNode(value);
				div.appendChild(text);
			}
			board.appendChild(div);
		}
	}

	// draw score
	var score = document.getElementById('score');
	while( score.firstChild ) {
		score.removeChild(score.firstChild);
	}
	score.appendChild(document.createTextNode(field.Score()));

}

function toogleHelp() {
	var score = document.getElementById('hint');
	score.hidden = !score.hidden;
}

function handleKey(event) {
	var keymaps = {
		37:	game.Left,  // left
		40: game.Down,  // down
		38: game.Up,    // up
		39: game.Right, // right

		65:	game.Left,  // a
		83: game.Down,  // s
		87: game.Up,    // w
		68: game.Right, // d

		72:	game.Left,  // h
		74: game.Down,  // j
		75: game.Up,    // k
		76: game.Right, // l
	}
	var keyCode = ('which' in event) ? event.which : event.keyCode;

	if (keyCode == 191) {
		// /
		toogleHelp();
		return;
	}

	var dir = keymaps[keyCode];
	if (dir > 0) {
		var moved = field.Move(dir);
		if (moved) {
			field.AddPoint();
		}
	}
	drawField();
}

</script>
<style>
#mainBoard
{
	width:160px;
	height:160px;
	float:center;
	/* border:1px solid black; */
}

.boardCell
{
	width:38px;
	height:38px;
	float:left;
	border:1px solid black;
}

</style>
</head>
<body onload="startx()" onkeydown="handleKey(event)">
<center>
	<div id="content">
		<h1>Fibonacci game</h1>
		<p>Score:&nbsp;<span id="score"></div></p>
		<br/>
		<p><div id="mainBoard"></div></p>
		<br/>
		<p><span id="sequence"></span></p>
		<br />
		<p><span id="hint"><b>How-to play:</b> use arrow keys (or WASD or even HJKL) to move tiles, try summing Fibonacci numbers!</span></p>
	</div>
</center>

</body>
</html>
<!-- vim: set ft=html: -->
